---

language: python
python: "2.7"

sudo: required

env:
  - distribution: centos
    version: 7
  - distribution: ubuntu
    version: xenial
  - distribution: ubuntu
    version: trusty
  - distribution: debian
    version: stretch
  - distribution: debian
    version: jessie

services:
  - docker

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=tests/travis/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible tests/travis'

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/zabbix-agent:ro ${distribution}-${version}:ansible > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/zabbix-agent/tests/test.yml --syntax-check'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/zabbix-agent/tests/test.yml'
  - >
    sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/zabbix-agent/tests/test.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  - 'echo "Changed tasks:"; sudo docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/zabbix-agent/tests/test.yml | grep -i "changed"; echo "###"'
  - 'sudo docker exec "$(cat ${container_id})" zabbix_agentd -V'
  - 'sudo docker exec "$(cat ${container_id})" zabbix_agentd --test "system.uname"'
  - 'sudo docker exec "$(cat ${container_id})" grep -v ^# /etc/zabbix/zabbix_agentd.conf'
  - 'sudo docker rm -f "$(cat ${container_id})"'

...
