---

- name: install firewalld
  package:
    name: firewalld
    state: present
  notify:
    - restart agent

- name: start and enable firewalld
  service:
    name: firewalld
    state: started
    enabled: yes

- name: add firewalld service
  template:
    src: templates/zabbix_service.j2
    dest: /etc/firewalld/services/zabbix-agent.xml
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: hack to get new service
  shell: >
    firewall-cmd --reload
  args:
    warn: no
  changed_when: no

- name: allow zabbix traffic on {{ firewalld_zone }} zone
  firewalld:
    service: zabbix-agent
    state: enabled
    immediate: yes
    permanent: yes
    zone: "{{ firewalld_zone }}"

...
