---

- name: invoke cleaning package cache
  import_tasks: cln_pkg_cache.yaml

- name: add zabbix repo
  yum_repository:
    name: "zabbix"
    description: 'Zabbix Official Repository - $basearch'
    baseurl: "http://repo.zabbix.com/zabbix/{{ zabbix_version  }}/rhel/{{ ansible_distribution_major_version }}/$basearch"
    enabled: 'yes'
    gpgcheck: "no"
    gpgkey: "{{ zabbix_repo_gpg_rpm }}"

- name: install agent
  yum:
    name: "zabbix-agent"
    state: "present"
  notify:
    - restart agent

- name: invoke cleaning package cache
  import_tasks: cln_pkg_cache.yaml
...
