---

version: '2'
jobs:
  build:
    branches:
    docker:
      - image: 'debian:buster'
    steps:
      - checkout:
      - run:
          command: |
            ls -lha
            pwd
            env

          

...
