---

version: '2'
jobs:
  build:
    branches:
    docker:
      - image: 'debian:buster'
    steps:
      - checkout:
          path: "${CIRCLE_WORKING_DIRECTORY}/test"
      - run:
          command: |
            ls -lRha

      - run:
          command: |
            echo 'export PATH=/path/to/foo/bin:$PATH' >> $BASH_ENV
            echo 'export VERY_IMPORTANT=$(cat important_value)' >> $BASH_ENV
            source $BASH_ENV

            echo 'list current dir'
            ls -lha
            
            echo 'list home'
            ls -lha ~/

            echo 'list project dir'
            ls -lha ~/project

            echo 'list using env var'
            ls -lha ${CIRCLE_WORKING_DIRECTORY}

            pwd
            env

          

...
