---

version: '2'
jobs:
  build:
    branches:
    docker:
      - image: 'debian:buster'
    steps:
      - checkout:
      - run:
          command: |
            ls -lha
            echo HOME
            ls -lha ~/
            echo workdir
            ls -lha ${CIRCLE_WORKING_DIRECTORY}
            pwd
            env

          

...
