---

version: '2'
jobs:
  build:
    branches:
    docker:
      - image: 'debian:buster'
    steps:
      - run:
          name: "install ansible"
          command: |
            apt-get update
            apt-get install ansible -y
      - checkout:
          path: "/etc/ansible/roles"
      - run:
          name: test
          command: |
            ls -lha
            env
            pwd
      - run:
          name: "do syntax check for test playbook"
          command: |
            ansible-playbook -v --syntax-check ./tests/test.yml

...
