---

version: '2'
jobs:
  build:
    branches:
    docker:
      - image: 'debian:buster'
    steps:
      - checkout:
      - run:
          name: "install ansible"
          command: |
            apt-get update
            apt-get install ansible -y
      - run:
          name: "fix role name"
          command: "sed -i 's/zabbix-agent/project/' tests/test.yml"
      - run:
          name: "redefine ansible roles dir"
          command: |
            echo 'export ANSIBLE_ROLES_PATH="~/"' >> $BASH_ENV
      - run:
          name: "do syntax check for test playbook"
          command: >
            ansible-playbook
            -v --syntax-check
            ~/project/tests/test.yml

...
