---

version: '2'
jobs:
  build:
    branches:
    docker:
      - image: 'debian:buster'
    steps:
      - run:
          name: "install ansible"
          command: |
            apt-get update
            apt-get install ansible -y
      - checkout:
          path: "/etc/ansible/roles/${CIRCLE_PROJECT_REPONAME}"
      - run:
          name: test
          command: |
            ls -lha /etc/ansible/roles/
            env
            pwd
      - run:
          name: "do syntax check for test playbook"
          command: |
            ansible-playbook -v --syntax-check /etc/ansible/roles/${CIRCLE_PROJECT_REPONAME}/tests/test.yml

...
