---

version: '2'
jobs:
  build:
    branches:
    docker:
      - image: 'debian:buster'
        environment:
          ANSIBLE_ROLES_PATH: ${HOME}

    steps:
      - run:
          name: "print env"
          command: |
            env
      - run:
          name: "install ansible"
          command: |
            apt-get update
            apt-get install ansible -y
      - run:
          name: "do checkout"
          checkout:
            path: "/etc/ansible/roles"
      - run:
          name: test
          command: |
            ls -lha
            env
            pwd
      - run:
          name: "do syntax check for test playbook"
          command: |
            ansible-playbook -v --syntax-check ./tests/test.yml

...
