---

version: '2'
jobs:
  build:
    branches:
    docker:
      - image: 'debian:buster'
    steps:
      - checkout:
      - run:
          command: |
            echo 'list current dir'
            ls -lha
            
            echo 'list home'
            ls -lha ~/

            echo 'list project dir'
            ls -lha ~/project

            echo 'list using env var'
            ls -lha ${CIRCLE_WORKING_DIRECTORY}

            pwd
            env

          

...
