---

version: '2'
jobs:
  build:
    branches:
    docker:
      - image: 'debian:buster'
    steps:
      - checkout:
      - run:
          name: "install ansible"
          command: |
            apt-get update
            apt-get install python python-pip virtualenv ansible -y
      - run:
          name: "prep"
          command: >
            echo 'export ANSIBLE_FORCE_COLOR="1"' >> $BASH_ENV &&
            echo 'export ANSIBLE_ROLES_PATH="~/"' >> $BASH_ENV &&
            sed -i 's/zabbix-agent/project/' tests/test.yml
      - run:
          name: "do syntax check for test playbook"
          command: >
            ansible-playbook
            -i tests/inventory
            -v --syntax-check
            tests/test.yml

      - run:
          name: "run once with diff"
          command: >
            ansible-playbook
            -i tests/inventory
            -v --diff
            tests/test.yml

...
