---

version: '2'
jobs:
  build:
    branches:
    docker:
      - image: 'debian:buster'
        environment:
          ANSIBLE_ROLES_PATH: $CIRCLE_WORKING_DIRECTORY

    steps:
      - checkout:
      - run:
          name: "workdir listing"
          command: |
            pwd
            ls -lha
            env
      - run:
          name: "install ansible"
          command: |
            apt-get update
            apt-get install ansible -y
      - run:
          name: "do syntax check for test playbook"
          command: |
            ansible-playbook -v --syntax-check ${CIRCLE_WORKING_DIRECTORY}/${CIRCLE_PROJECT_REPONAME}/tests/test.yml

...
