---

version: '2'
jobs:
  build:
    docker:
      - image: 'debian:buster'

    steps:
      - checkout:
      - run:
          name: "workdir listing"
          command: 'pwd && ls -lha'
      - run:
          name: "install ansible"
          command: "apt-get update && apt-get install ansible"
      - run:
          name: "do syntax check for test playbook"
          command: "ansible-playbook -v --syntax-check ./tests/test.yml"

...
