FROM ubuntu:xenial

RUN apt-get update && apt-get dist-upgrade -y && apt-get install -y software-properties-common && rm -rf /var/lib/apt/lists/*

RUN apt-add-repository -y ppa:ansible/ansible && apt-get update && apt-get install -y \
    git \
    ansible \
    ca-certificates \
    curl \
    gnupg \
    dbus \
 && rm -rf /var/lib/apt/lists/*

RUN systemctl start dbus || /etc/init.d/dbus start

RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

CMD ["/sbin/init"]
